#!/usr/bin/perl -w
# Copyright (c) 2014 SUSE Linux Products GmbH
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# dump modalias and filesytem supplements of the solv files specified on the command line

use strict;
use solv;
use File::Basename;

my $pool = solv::Pool->new();

for my $fn (@ARGV) {
	my $name = basename($fn);
	$name =~ s/\.solv$//;
	my $repo = $pool->add_repo($name);
	$repo->add_solv ($fn);
}

$pool->addfileprovides();
# will segfault if you don't do that!
$pool->createwhatprovides();

my $sel = $pool->Selection();
for my $d (@{$pool->solvables_iter()}) {
	$sel->add_raw($solv::Job::SOLVER_SOLVABLE, $d->{id});
}

my %suppl;
for my $s ($sel->solvables()) {
	for my $dep ($s->lookup_deparray($solv::SOLVABLE_SUPPLEMENTS)) {
		my $str = $dep->str();
		next unless $str =~ /^namespace:(?:modalias|filesystem)/;
		$suppl{$str} = 1;
	}
}

for my $str (sort keys %suppl) {
	printf "namespace %s \@SYSTEM\n", $str;
}
